"""add percent

Revision ID: 0d374b570e4b
Revises: 1765df165ab3
Create Date: 2025-05-20 00:15:57.025466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d374b570e4b'
down_revision: Union[str, None] = '1765df165ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins', 'percent')
    # ### end Alembic commands ###
