"""init

Revision ID: 2f8e64b5c37b
Revises: 
Create Date: 2025-07-23 09:18:50.363618

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f8e64b5c37b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_at_1_day', sa.Float(), nullable=True),
    sa.Column('price_at_7_day', sa.Float(), nullable=True),
    sa.Column('price_at_30_day', sa.Float(), nullable=True),
    sa.Column('update_mode', sa.Enum('HIGH', 'MEDIUM_WELL', 'MEDIUM', 'LOW', name='skinupdatemode'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('idx_skin_update_mode', 'skins', ['update_mode'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=True),
    sa.Column('steam_name', sa.String(), nullable=True),
    sa.Column('steam_avatar', sa.String(), nullable=True),
    sa.Column('steam_profile_link', sa.String(), nullable=True),
    sa.Column('skin_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_steam_id', 'users', ['steam_id'], unique=False)
    op.create_table('skins_price_history',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skin_name'], ['skins.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_skin_price_history_name', 'skins_price_history', ['skin_name'], unique=False)
    op.create_index('idx_skin_price_history_timestamp', 'skins_price_history', ['timestamp'], unique=False)
    op.create_table('users_skins',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['skin_name'], ['skins.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_skin_at_user_id', 'users_skins', ['user_id'], unique=False)
    op.create_index('idx_skin_at_user_name', 'users_skins', ['skin_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_skin_at_user_name', table_name='users_skins')
    op.drop_index('idx_skin_at_user_id', table_name='users_skins')
    op.drop_table('users_skins')
    op.drop_index('idx_skin_price_history_timestamp', table_name='skins_price_history')
    op.drop_index('idx_skin_price_history_name', table_name='skins_price_history')
    op.drop_table('skins_price_history')
    op.drop_index('idx_user_steam_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_skin_update_mode', table_name='skins')
    op.drop_table('skins')
    # ### end Alembic commands ###
