"""price_chart to string

Revision ID: 8a4a9f82a175
Revises: 
Create Date: 2025-05-24 21:22:09.833629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4a9f82a175'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('update_time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('skins',
    sa.Column('skin_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('price_chart', sa.String(), nullable=True),
    sa.Column('owner', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('skin_id'),
    sa.UniqueConstraint('skin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins')
    op.drop_table('users')
    # ### end Alembic commands ###
